### PR TITLE
[master] Address selinux denials

### PR DESCRIPTION
**Pull request by humberos**
Fix tad, gatekeeperd, mm-camerad and priv_app denials.

Special attention on tad change which is the critical process.

All changes were tested on karin.

### CODE REVIEW

**Comment by alviteri** [comment]
@humberos drmserver needs to be fixed in system/sepolicy check it ... And send the patch to google

**Comment by alviteri** [comment]
https://android.googlesource.com/platform/system/sepolicy/+/android-7.0.0_r6/drmserver.te

**Comment by humberos** [comment]
removed!
thanks.

**Comment by alviteri** [comment]
It is practically visible on all .... Also Nexus devices ... I saw it in angler

**Comment by humberos** [comment]
https://android-review.googlesource.com/#/c/249448/1

**Pull request closed without merging**
