### PR TITLE
sepolicy: Clean up 7328924 to match other rules (netmgrd)

### PR DESCRIPTION
**Pull request by luk1337**

### CODE REVIEW

**Comment by luk1337** [comment]
@jerpelea untested (guess why) but it should work.

**Comment by luk1337** [comment]
oops, wrong commit id.

**Comment by oshmoun** [comment]
looks like some further perms are needed:
01-18 20:14:27.203  2737  2737 W Loc_hal : type=1400 audit(0.0:57): avc: denied { search } for name="qmux_radio" dev="tmpfs" ino=11312 scontext=u:r:hal_gnss_qti:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=dir permissive=0

**Comment by luk1337** [comment]
oh, so it actually needs the 'r' part. Interesting

**Comment by alviteri** [comment]
@luk1337 there is a read denial even on 8.1
01-19 11:20:16.567   645   645 W pcid-lo : type=1400 audit(0.0:6670): avc: denied { read } for name="qmux_gps" dev="tmpfs" ino=3742 scontext=u:r:location:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=dir permissive=0

**Comment by luk1337** [comment]
Now that's something that has to do with location. Updated patch back to rw_file_perms.

**Pull request merged**
