### PR TITLE
[master] Fix mediacodec, mediaextractor, bluetooth, timkeep, hal_graphics_composer_default and system_server permissions

### PR DESCRIPTION
**Pull request by humberos**
based on suzu logs

### CODE REVIEW

**Comment by AdFad666** [comment]
I'm missing a description on how to reproduce this. What actions did you perform to trigger these denials? If I can reproduce, I can review this more efficiently.

**Comment by humberos** [comment]
please, hold on since there are more system_server denials that are breaking boot process when enforcing mode is on! thanks!

**Comment by humberos** [comment]
@AdFad666 
unfortunately we can't get all denials by triggering logcat or dmesg once .... some major denials will appear after one fix then we need to collect logs again and again...

**Comment by humberos** [comment]
The main step to reproduce those denials is "Enforce mode ON".

**Comment by humberos** [comment]
the timekeep one requires this https://github.com/sonyxperiadev/device-sony-common/pull/366

**Comment by oshmoun** [comment]
seems mediaextractor needs a bit more to work ok, currently can't play music from sdcard:
```
[  283.658704] type=1400 audit(1513290552.998:755): avc: denied { getattr } for pid=2514 comm="Binder:759_3" path=2F6D6E742F6D656469615F72772F363234442D314631392F4D757369632F706572736F6E6120352F303520547261636B20352E6F6767 dev="mmcblk1p1" ino=388 scontext=u:r:mediaextractor:s0 tcontext=u:object_r:vfat:s0 tclass=file permissive=0
[  283.661313] type=1400 audit(1513290552.998:755): avc: denied { getattr } for pid=2514 comm="Binder:759_3" path=2F6D6E742F6D656469615F72772F363234442D314631392F4D757369632F706572736F6E6120352F303520547261636B20352E6F6767 dev="mmcblk1p1" ino=388 scontext=u:r:mediaextractor:s0 tcontext=u:object_r:vfat:s0 tclass=file permissive=0
[  283.661497] type=1400 audit(1513290553.000:756): avc: denied { read } for pid=2514 comm="Binder:759_3" path=2F6D6E742F6D656469615F72772F363234442D314631392F4D757369632F706572736F6E6120352F303520547261636B20352E6F6767 dev="mmcblk1p1" ino=388 scontext=u:r:mediaextractor:s0 tcontext=u:object_r:vfat:s0 tclass=file permissive=0
```

**Comment by humberos** [comment]
Oh! Thanks!
I will upload new patchset

**Comment by oshmoun** [comment]
can confirm that music playback from sdcard is working with this now

**Pull request merged**
