### PR TITLE
[VERIFYME] [Q] cleanup file contexts

### PR DESCRIPTION
**Pull request by ix5**
Some cleanup, moved /dsp location, and include keylayout files in `/system/vendor`.

**VERIFYME** on the `rfs_system_file` please!

### CODE REVIEW

**Comment by jerpelea** [comment]
please rebase

**Comment by ix5** [comment]
The `sphal` removal is speculative, need to test.

@jerpelea is the `rfs` removal ok?

**Comment by jerpelea** [comment]
no

**Comment by ix5** [comment]
Let's ignore this for now

**Pull request closed without merging**
