### PR TITLE
sepolicy: add rild2 and rild-debug2 socket devices

### PR DESCRIPTION
**Pull request by pablomh**
Sort in alphabetical order while here

### CODE REVIEW

**Comment by alviteri** [comment]
Remove white string 132

**Comment by pablomh** [comment]
Done.

**Comment by jerpelea** [comment]
are you using 3.18 kernel ?

**Comment by alviteri** [comment]
Alien should be the same for 3.18 since is dsds target

**Comment by jerpelea** [comment]
i know this but i am trying to understand if pablomh is using the proper branch

**Comment by pablomh** [comment]
My tests were done in 3.10 (using 7.1-legacy branch from SonyAosp) and this is a "forward"-port.

I don't know of anyone with a DSDS 3.18 device who could test this, though.

**Comment by jerpelea** [comment]
you should use the n-mr1 branch with 3.10 kernel 
please test and push also on n-mr1 branch

**Pull request merged**
