### PR TITLE
[DO NOT MERGE] sony: sepolicy: Address denials for timekeep

### PR DESCRIPTION
**Pull request by humberos**
This change is based on:
========================

From 91f003b489a066e12a05fcbb68484151fe16cbd5 Mon Sep 17 00:00:00 2001
From: Humberto Borba <humberos@gmail.com>
Date: Thu, 9 Jun 2016 20:08:43 -0300
Subject: [PATCH] Fix sepolicy permissions

-----------------------------------------------------------------------
Move timekeep_app to system_app domain and fix property_socket permissions
-----------------------------------------------------------------------
avc: denied { write } for name="property_service" dev="tmpfs" ino=12135
scontext=u:r:timekeep_app:s0 tcontext=u:object_r:property_socket:s0
tclass=sock_file permissive=0

avc: denied { connectto } for path="/dev/socket/property_service"
scontext=u:r:timekeep_app:s0 tcontext=u:r:init:s0
tclass=unix_stream_socket permissive=0

AND
===

From caa3b8c33e9acc59cdda0c2bef392f71c0ce15e3 Mon Sep 17 00:00:00 2001
From: Humberto Borba <humberos@gmail.com>
Date: Wed, 6 Jul 2016 23:32:30 -0300
Subject: [PATCH] sony: sepolicy: Address denials for timekeep

avc: denied { fowner } for pid=444 comm="timekeep" capability=3
scontext=u:r:timekeep:s0 tcontext=u:r:timekeep:s0 tclass=capability permissive=0

avc: denied { fsetid } for capability=4 scontext=u:r:timekeep:s0
tcontext=u:r:timekeep:s0 tclass=capability permissive=0

Signed-off-by: Humberto Borba <humberos@gmail.com>
Change-Id: I9f1d283b58bce1b8c86f74b9ec1fb56b8095b171

### CODE REVIEW

**Comment by humberos** [comment]
Ping @alviteri

**Comment by alviteri** [comment]
@humberos 

libsepol.report_failure: neverallow on line 303 of system/sepolicy/domain.te (or line 8971 of policy.conf) violated by allow system_app system_app_data_file:file { execute execute_no_trans };
libsepol.check_assertions: 1 neverallow failures occurred

**Comment by humberos** [comment]
@alviteri 
please let me know about denials.
thank you.

**Comment by alviteri** [comment]
@humberos all timekeep stuff here

david@david-desktop:~/Scaricati$ adb logcat | grep timekeep
08-26 13:30:53.897  1182  1182 I PackageManager: Adjusting ABI for com.sony.timekeep to armeabi-v7a (requirer=android, scannedPackage=null)
08-26 13:30:53.979   384   384 I installd: type=1400 audit(0.0:14): avc: denied { getattr } for path="/data/data/com.sony.timekeep/lib" dev="mmcblk0p25" ino=48718 scontext=u:r:installd:s0 tcontext=u:object_r:timekeep_app_data_file:s0 tclass=lnk_file permissive=1
08-26 13:30:53.979   384   384 I installd: type=1400 audit(0.0:15): avc: denied { unlink } for name="lib" dev="mmcblk0p25" ino=48718 scontext=u:r:installd:s0 tcontext=u:object_r:timekeep_app_data_file:s0 tclass=lnk_file permissive=1
08-26 13:30:53.979   384   384 I installd: type=1400 audit(0.0:16): avc: denied { create } for name="lib" scontext=u:r:installd:s0 tcontext=u:object_r:timekeep_app_data_file:s0 tclass=lnk_file permissive=1
08-26 13:31:01.759   384   384 I installd: type=1400 audit(0.0:19): avc: denied { getattr } for path="/data/data/com.sony.timekeep/lib" dev="mmcblk0p25" ino=48718 scontext=u:r:installd:s0 tcontext=u:object_r:timekeep_app_data_file:s0 tclass=lnk_file permissive=1
08-26 13:31:01.759   384   384 I installd: type=1400 audit(0.0:20): avc: denied { unlink } for name="lib" dev="mmcblk0p25" ino=48718 scontext=u:r:installd:s0 tcontext=u:object_r:timekeep_app_data_file:s0 tclass=lnk_file permissive=1
08-26 13:31:01.759   384   384 I installd: type=1400 audit(0.0:21): avc: denied { create } for name="lib" scontext=u:r:installd:s0 tcontext=u:object_r:timekeep_app_data_file:s0 tclass=lnk_file permissive=1
08-26 13:32:20.386  1182  2080 I ActivityManager: Start proc 4077:com.sony.timekeep/1000 for broadcast com.sony.timekeep/.TimeKeep
08-26 13:32:20.476  4077  4077 D TimeKeep-Receiver: Got intent Intent { act=android.intent.action.TIME_SET flg=0x24000010 cmp=com.sony.timekeep/.TimeKeep }, storing time delta.
08-26 13:32:20.479  4077  4077 I m.sony.timekeep: type=1400 audit(0.0:28): avc: denied { write } for name="ats_2" dev="mmcblk0p25" ino=535394 scontext=u:r:timekeep_app:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
08-26 13:32:20.479  4077  4077 I m.sony.timekeep: type=1400 audit(0.0:29): avc: denied { getattr } for path="/data/time/ats_2" dev="mmcblk0p25" ino=535394 scontext=u:r:timekeep_app:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
^Z
[2]+  Fermato                 adb logcat | grep --color=auto timekeep

**Comment by alviteri** [comment]
david@david-desktop:~/Scaricati$ adb logcat | grep timekeep
08-26 14:11:17.044  1172  1172 I PackageManager: Adjusting ABI for com.sony.timekeep to armeabi-v7a (requirer=android, scannedPackage=null)
^Z
[1]+  Fermato                 adb logcat | grep --color=auto timekeep

is ok now merge

**Pull request merged**
