### PR TITLE
sony: sepolicy: Rebase sepolicy for project treble rules

### PR DESCRIPTION
**Pull request by humberos**
It is the first kick for the project rebase.

Attention!!!
It needs to be tested on all platforms but loire (which I already did).

There is a document that will guide us with this task.
https://source.android.com/security/selinux/images/SELinux_Treble.pdf

### CODE REVIEW

**Comment by alviteri** [comment]
@humberos to do this you can follow this struct
https://android.googlesource.com/platform/system/sepolicy/+/android-9.0.0_r6/Android.mk#70

**Comment by humberos** [comment]
@alviteri I will test it, thank you!
btw, I am following qcom!

**Comment by alviteri** [comment]
Tone yoshino ok ...

**Comment by jerpelea** [comment]
nile?

**Comment by jerpelea** [comment]
loire?

**Pull request merged**
