### PR TITLE
sepolicy: improve file_contexts

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by oshmoun** [comment]
aren't file contexts used at build time to set the correct contexts for the generated files? if that's the case, then removing system/vendor paths will mean that the files will not get assigned their correct contexts.

**Comment by alviteri** [comment]
Just see the files under (odm|vendor) that mean (odm|vendor|system|vendor) is missing!

**Comment by alviteri** [comment]
ping @luk1337

**Comment by luk1337** [comment]
I looked at this like yesterday, it seems ok.

**Pull request merged**
