### PR TITLE
sepolicy: avoid kernel 4.9 denials

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by oshmoun** [comment]
On which platform do those appear? allowing tracing_on and sleep_disabled is unusual

**Comment by alviteri** [comment]
https://github.com/sonyxperiadev/device-sony-sepolicy/commit/b18c085364821aa82ff84a31003804fc87f7bb2f#diff-5b7f999fc2df325c492ca673130d5df7L18

here you go ... they were these

**Comment by alviteri** [comment]
for alin these were present on tama ... for me on nile ...

**Comment by alviteri** [comment]
actually caf defined "module/lpm_levels" but not "kernel/debug"

https://source.codeaurora.org/quic/la/device/qcom/sepolicy/tree/common/file_contexts?h=LA.UM.6.3.r6-02900-sdm845.0#n503

**Comment by jerpelea** [comment]
please remove kernel/debug

**Pull request closed without merging**
