### PR TITLE
[WIP] [o-mr1] Compatible props backports

### PR DESCRIPTION
**Pull request by ix5**
https://github.com/sonyxperiadev/packages_apps_ExtendedSettings/pull/47
https://github.com/sonyxperiadev/vendor-sony-oss-cash/pull/13
https://github.com/sonyxperiadev/timekeep/pull/21

### CODE REVIEW

**Comment by jerpelea** [comment]
is it tested on 8.1?

**Comment by ix5** [comment]
Not yet

**Comment by ix5** [comment]
Ping @jamuir
Are you or your company(?) still shipping Oreo builds?

**Comment by jamuir** [comment]
Yes, we are.

**Comment by jamuir** [comment]
@ix5 :  fyi, in our maple oreo images, TimeKeep is crashing because it cannot set `persist.vendor.timeadjust`:

```04-02 13:37:49.421  5299  5299 D TimeKeep-Receiver: u0 : Got intent Intent { act=android.intent.action.TIME_SET flg=0x25200010 cmp=com.sony.timekeep/.TimeKeep }, storing time delta.
04-02 13:37:49.422  5299  5299 D TimeKeep-Receiver: u0 : Setting adjust property to 1544535656
04-02 13:37:49.423  2614  5251 E WakeLock: u0 : GCM_HB_ALARM release without a matched acquire!
04-02 13:37:49.423  5299  5299 W libc    : Unable to set property "persist.vendor.timeadjust" to "1544535656": error code: 0x18
04-02 13:37:49.423  5299  5299 D AndroidRuntime: Shutting down VM
--------- beginning of crash
04-02 13:37:49.424  5299  5299 E AndroidRuntime: FATAL EXCEPTION: main
04-02 13:37:49.424  5299  5299 E AndroidRuntime: Process: com.sony.timekeep, PID: 5299
04-02 13:37:49.424  5299  5299 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.sony.timekeep.TimeKeep: java.lang.RuntimeException: failed to set system property
04-02 13:37:49.424  5299  5299 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
04-02 13:37:49.424  5299  5299 E AndroidRuntime: 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
04-02 13:37:49.424  5299  5299 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
04-02 13:37:49.424  5299  5299 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-02 13:37:49.424  5299  5299 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
04-02 13:37:49.424  5299  5299 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
04-02 13:37:49.424  5299  5299 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 13:37:49.424  5299  5299 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
04-02 13:37:49.424  5299  5299 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
04-02 13:37:49.424  5299  5299 E AndroidRuntime: Caused by: java.lang.RuntimeException: failed to set system property
04-02 13:37:49.424  5299  5299 E AndroidRuntime: 	at android.os.SystemProperties.native_set(Native Method)
04-02 13:37:49.424  5299  5299 E AndroidRuntime: 	at android.os.SystemProperties.set(SystemProperties.java:155)
04-02 13:37:49.424  5299  5299 E AndroidRuntime: 	at com.sony.timekeep.TimeKeep.onReceive(TimeKeep.java:69)
04-02 13:37:49.424  5299  5299 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
04-02 13:37:49.424  5299  5299 E AndroidRuntime: 	... 8 more
```

**Comment by ix5** [comment]
Hey James, thanks for testing, you may be the last holdout on 8.1 :)
Your log puzzles me a bit, `persist.vendor.timeadjust` is labeled and the relevant domains have access.
Can you check whether you see an `avc: denied` message anywhere?

But good to see this compiles (as it should, it's a minor change) and after we know the timekeep issue this should be good to merge.

**Comment by jamuir** [comment]
> Your log puzzles me a bit, persist.vendor.timeadjust is labeled and the relevant domains have access.
> Can you check whether you see an avc: denied message anywhere?

sorry -- the failure I posted was from a normal sony 8.1 tree and does not include your sepolicy changes.  I just wanted to point out that the current 8.1 tree is broken.  I am sure your PR will fix the timekeep error.

I will try a new build with your changes and let you know.

**Comment by jamuir** [comment]
@ix5 since it is merged now, I guess I can just build from the updated tree :-)

One thing I noticed:  in the oreo tree ExtendedSettings uses the branch "o-mr1".  I don't think you made any property changes to that branch, but that seems ok since your sepolicy changes are still compatible with the non-vendor properties used on the o-mr1 branch.

**Comment by ix5** [comment]
You're right, my caution paid off then.

**Pull request merged**
