### PR TITLE
sepolicy: cleanup sepolicy according to CAF

### PR DESCRIPTION
**Pull request by alviteri**
based on https://source.codeaurora.org/quic/la/device/qcom/sepolicy/tree/?h=LA.UM.6.4.r1-03200-8x98.0

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by jerpelea** [comment]
this commit will break broadcom devices

**Comment by alviteri** [comment]
will build dora in few minutes
and report

**Comment by alviteri** [comment]
screenshot_20171007-232804


@jerpelea bt up on bcm

**Comment by alviteri** [comment]
This fixes these denials still present on ttyMSM and ttyHS0 on qcom

**Pull request merged**
