### PR TITLE
sepolicy: Allow nfc service access

### PR DESCRIPTION
**Pull request by alviteri**
11-23 21:38:31.704   553   553 E SELinux : avc:  denied  { find } for service=nfc pid=1302 uid=10029 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:nfc_service:s0 tclass=service_manager

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
@AdFad666

**Comment by alviteri** [comment]
Since there is not answer I am closing this .... Will put this on my vendor sepolicy

**Comment by AdrianDC** [comment]
What about giving a bit more care about everyone's life and timings ?

If Adam didn't see this PR yet or didn't have time to review it within 48 hours, it's not a disaster.

I'm personally fine with that allow, although you could also use the same commit from CodeAurora : https://review.lineageos.org/#/c/193234/

**Comment by jerpelea** [comment]
@alvideri 
please don't close valid comits

**Comment by alviteri** [comment]
@jerpelea is this valid or not ?

**Pull request closed without merging**
