### PR TITLE
[WIP] Change to compatible props

### PR DESCRIPTION
**Pull request by ix5**
The props are being renamed to conform to "compatible" prop usage.

### CODE REVIEW

**Comment by ix5** [comment]
Needed changes:
- https://github.com/sonyxperiadev/packages_apps_ExtendedSettings/pull/47
- https://github.com/sonyxperiadev/device-sony-common/pull/589
- https://github.com/sonyxperiadev/timekeep/pull/21/
- https://github.com/sonyxperiadev/vendor-sony-oss-cash/pull/13
- `netmgrd` change to `persist.vendor.net.doxlat`

TODOs:https://github.com/sonyxperiadev/vendor-sony-oss-cash/pull/13
- Check if `cameraserver` also needs to read CASH props
- Check if `gatekeeperd` also needs `vendor.sys.keymaster.loaded`
- Check and fix `get_prop(hal_audio_default, bluetooth_prop)`
- Check and fix `et_prop(hal_camera_default, camera_prop)`
- Check if `set_prop(hal_camera_default, vendor_cash_prop)` is needed
- Check if `(vendor.)persist.net.doxlat` is enough for `netmgrd`(looks that way)
- Check if `get_prop` is enough for `system_app` -> `persist.vendor.timeadjust`

**Comment by jerpelea** [comment]
please rebase and split in logical patches

**Comment by jerpelea** [comment]
@ix5

**Comment by ix5** [comment]
Rebased and split

**Pull request merged**
