### PR TITLE
suppress denial logspam

### PR DESCRIPTION
**Pull request by alviteri**
These denials are not causing app bugs but the underlying code needs
to be fixed. In the meantime, remove them from the logs.

Bug: 63631799
Test: Build and flash, verify denials are gone.
Change-Id: I6ddc91aa792b771e2c4190b211588347cc4119ea

### CODE REVIEW

**Comment by jerpelea** [comment]
@AdFad666 @AdrianDC

**Comment by AdrianDC** [comment]
I don't really like this.

As it widely silences proc: and device: for example, it could miss real denials that we would want to care about and to fix, except they wouldn't show unless this is reverted / removed on purpose.

I prefer using dontaudit only on very specific denials that we know to be irrelevant, example :
https://github.com/LineageOS/android_device_sony_huashan/blob/lineage-15.0/sepolicy/dontaudit.te
https://github.com/LineageOS/android_device_sony_huashan/commit/bc4d7444082eb16e48a8f21eebbbce4866c4afdb#diff-d54a18733b359d66154d1dc5fa179049

**Comment by alviteri** [comment]
We don't have them

**Comment by alviteri** [comment]
@adrianDC we have some priv_app denials same which wahoo have dontaudit due to same spam reason

**Comment by AdrianDC** [comment]
I believe you have, otherwise I hope you wouldn't be pushing this commit.

I'm just worried you're not going to hide too generic nodes / denials with this, which would later need to be fixed but will go unnoticed because they'll be ignored.

Also we don't know what specific denials this concerns, please comment with some related denial logs here.

**Comment by alviteri** [comment]
Adrian the denials are numerous for example https://github.com/sonyxperiadev/device-sony-sepolicy/pull/269/commits/8768a85140e270dc194213316f27c6a08049ca5e
The priv_app one

**Comment by AdrianDC** [comment]
You're showing me that we did resolve some priv_app denials in the past, and at the same time, you want to "donotaudit" some of these denials.

donotaudit doesn't allow at all, it simply hides denials we know 100% to be invalid or irrelevant, hence I'll stay on what I said in my previous comment.

**Pull request closed without merging**
