### PR TITLE
sepolicy: add policy for exFAT

### PR DESCRIPTION
**Pull request by alviteri**
needed by custom roms using exFAT tool for externalSD

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
@kholk

**Comment by alviteri** [comment]
let exfat SDs to be read/write under enforcing selinux

**Comment by luk1337** [comment]
Doesn't that belong to same category as widevine aka not something we want in SOD?

**Comment by luk1337** [comment]
Also this is not device specific sepolicy, if you want to support exfat in your project I would recommend using your own vendor/xxx or simply adding it to system/sepolicy.

**Comment by alviteri** [comment]
I am adding here due to @kholk suggestion

**Comment by luk1337** [comment]
then i don't really agree with that suggestion as this is repository for device sepolicy not platform/system specific sepolicy.

**Comment by luk1337** [comment]
Also it'll conflict with custom ROMs so -2

**Comment by kholk** [comment]
This is NOT for kernel exfat (which is not open source and available only with license). Also, this introduces support for FUSE file systems, hence my suggestion of creating a PR.

**Comment by luk1337** [comment]
doesn't matter, it conflicts with custom roms and should be in system sepolicy.

**Pull request closed without merging**
