### PR TITLE
label sys/devices/dsi_panel_driver/pcc_profile as sysfs_pcc_profile

### PR DESCRIPTION
**Pull request by alviteri**
avoid

01-23 23:46:19.699  5439  5439 W xtendedsettings: type=1400 audit(0.0:190): avc: denied { write } for name=pcc_profile dev=sysfs ino=51797 scontext=u:r:system_app:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by MarijnS95** [comment]
Thanks for following this up from https://github.com/sonyxperiadev/packages_apps_ExtendedSettings/pull/41!

**Comment by alviteri** [comment]
This one is needed by akari .. or under enforcing selinux it will not work lol

**Comment by MarijnS95** [comment]
It's needed for any SDE device since the dsi panel driver path changed :smile:

**Comment by alviteri** [comment]
well I didn't see nile yet lol

**Pull request merged**
