### PR TITLE
sepolicy: avoid init denials

### PR DESCRIPTION
**Pull request by alviteri**
03-20 01:45:11.732     1     1 I init    : type=1400 audit(0.0:14): avc: denied { write } for name=idVendor dev=configfs ino=14872 scontext=u:r:init:s0 tcontext=u:object_r:configfs:s0 tclass=file permissive=1
03-20 01:45:11.858     1     1 W init    : type=1400 audit(0.0:19): avc: granted { read open } for path=/dev/ttyMSM0 dev=tmpfs ino=14520 scontext=u:r:init:s0 tcontext=u:object_r:tty_device:s0 tclass=chr_file

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
@AdFad666

**Comment by alviteri** [comment]
Just second commit ?

**Comment by AdFad666** [comment]
@alviteri see https://github.com/sonyxperiadev/device-sony-sepolicy/pull/291 for examples of how to do it

**Comment by AdrianDC** [comment]
Do not push an unrelated commit after the PR. This is concerning init, and you're adding a vendor related commit that is clearly not enforced.

The vendor commit has no denials logs.

Do not allow global "sysfs:file", it's a random permissive rule. Fix labelling first.

"allow wcnss_filter self:capability2 block_suspend;"
> Pointless as you already gave wakelock_use rights

"allow wcnss_filter init:unix_stream_socket connectto;"
> Pointless as you already gave it set_prop( rights, which implies "allow ... init:unix_stream_socket connectto;"

net_admin : You could add the net_admin group to the init .rc instead.

**Comment by alviteri** [comment]
Just to be clear the net_admin is wrong here but it is already merged ....

**Pull request closed without merging**
