### PR TITLE
Mm 6.0 revert

### PR DESCRIPTION
**Pull request by alviteri**

### CODE REVIEW

**Comment by alviteri** [comment]
@jerpelea @humberos proper fix
@AdFad666 

https://android-review.googlesource.com/#/c/252282/
https://android-review.googlesource.com/#/c/252283/

**Comment by humberos** [comment]
btw,
https://android-review.googlesource.com/#/c/198885/

**Comment by alviteri** [comment]
Did you check code?

**Comment by humberos** [comment]
@alviteri 
Although the aosp patch is already merged but it is not present in current/latest aosp tag.
Also, not sure if we should wait Nougat (which I think will come with the proper fix) then proceed with these reverts OR get these reverts now and update aosp build instructions. it is a @jerpelea 's prerogative.

**Comment by alviteri** [comment]
Well yeah my comment was for second commit which is different than that merged in master

**Comment by humberos** [comment]
@alviteri we are using the aosp merged change ( https://android-review.googlesource.com/#/c/198885/ ) in Omnirom.
But to be honest I haven't checked it yet so I don't know if it is enough to fix ioctl denials.
I will try these reverts later today then I will report back.

**Comment by alviteri** [comment]
@humberos I have them right now...  And can't see any trace of it

**Comment by humberos** [comment]
@alviteri 
Ok.
I have used https://android-review.googlesource.com/#/c/198885/  then revert both that you are PR'ing so the merged one is fixing the ioctl denials by itself.
Tested on kitakami karin.

**Comment by humberos** [comment]
So
we can use:
https://android-review.googlesource.com/#/c/198885/  [ merged ]

OR

https://android-review.googlesource.com/#/c/252282/
https://android-review.googlesource.com/#/c/252283/

**Comment by alviteri** [comment]
Did you try to do cherry-pick?  For me there are errors in merge

**Comment by humberos** [comment]
Nope. I am using it from Omni. I think we need to move to latest tag, r52 or r54 (bullhead)

**Comment by alviteri** [comment]
wiil not be merged .....

**Pull request closed without merging**
