### PR TITLE
9.0-bringup

### PR DESCRIPTION
**Pull request by alviteri**

### CODE REVIEW

**Comment by alviteri** [comment]
needed by
https://github.com/sonyxperiadev/device-sony-common/pull/505/commits/f98f536980a1b5266724a33e5cf6d18e4bfa2889
https://github.com/sonyxperiadev/device-sony-common/pull/505/commits/4bf7d2ac80d22d7c7d554621b5e2eb08bf715d12
https://github.com/sonyxperiadev/device-sony-common/pull/505/commits/f8bcca566ec15eadda9dc54ba07cb35da038bf55

**Comment by jerpelea** [comment]
please split the commit

https://github.com/sonyxperiadev/device-sony-sepolicy/pull/398/commits/ab11ae86fff717cb5714fff8a51d317399f635cf

**Comment by jerpelea** [comment]
please set PRODUCT_SHIPPING_API_LEVEL := 26 in your local tree

**Comment by alviteri** [comment]
why 26 ? not all supported devices were released with nougat

**Comment by MarijnS95** [comment]
@alviteri 26 is 8.0, 27 is 8.1.

What matters is that setting `PRODUCT_SHIPPING_API_LEVEL` to whatever causes `PRODUCT_FULL_TREBLE` to be set, in turn applying even more `neverallow` constraints to the sepolicy, with which we want to stay compatible.

**Comment by alviteri** [comment]
ok whatever but we should declare the shipping api level (real one)

**Comment by jerpelea** [comment]
libsepol.report_failure: neverallow on line 866 of system/sepolicy/public/domain.te (or line 11008 of policy.conf) violated by allow hal_camera_default camera_data_file:dir { search };
libsepol.check_assertions: 1 neverallow failures occurred

**Comment by jerpelea** [comment]
please rebase

**Comment by alviteri** [comment]
new start with PRODUCT_SHIPPING_API_LEVEL := 26 in local tree

**Comment by alviteri** [comment]
Thank you alin ... For some unknown reasons I don't have the flag set anymore ... I will be careful next time .....

**Comment by jerpelea** [comment]
please rebase

**Pull request merged**
