### PR TITLE
sepolicy: avoid some denials after rebase

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
bt is broken actually it is defined at odm/bin as start_hci_filter please @jerpelea be sure yo change it to wcnss_filter before compile again wcnss_filter

**Comment by jerpelea** [comment]
1 commit for each change with description why you do the change

**Comment by alviteri** [comment]
No it will not happen ... You can close sorry but not time

**Comment by jerpelea** [comment]
if we add bulk commits again it will endup in the same state as before cleanup

**Comment by jerpelea** [comment]
@AdFad666 please take the lead

**Comment by alviteri** [comment]
The bulk was the same base was used since marshmallow ...

**Comment by jerpelea** [comment]
yes but now it is time to improve

**Pull request closed without merging**
