### PR TITLE
sepolicy: do not label /proc/version

### PR DESCRIPTION
**Pull request by alviteri**
see luk1337 eplanation here https://github.com/sonyxperiadev/device-sony-sepolicy/pull/321

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
@luk1337

**Comment by luk1337** [comment]
That's still wrong, for example you didn't remove the declaration of `proc_version` leaving unnecessary junk in sepolicy.

**Comment by luk1337** [comment]
Also you don't really need to reformat the file while at it. I would prefer if you went for minimal delta/diff.

**Comment by alviteri** [comment]
updated thanks

**Pull request merged**
