### PR TITLE
[n-mr1] sony: sepolicy: Unify 3.10 and 3.18 requirements

### PR DESCRIPTION
**Pull request by humberos**
Change-Id: Id3cf10080b7fb888ca5b25f0c91911dcc37f0a93
Signed-off-by: Humberto Borba <humberos@gmail.com>

### CODE REVIEW

**Comment by rancidfrog** [comment]
Compile error when I try to build kernel:
```
libsepol.report_failure: neverallow on line 204 of system/sepolicy/untrusted_app.te (or line 19718 of policy.conf) violated by allow untrusted_app vfat:file { create };
libsepol.report_failure: neverallow on line 204 of system/sepolicy/untrusted_app.te (or line 19718 of policy.conf) violated by allow untrusted_app vfat:dir { create };
libsepol.check_assertions: 2 neverallow failures occurred
Error while expanding policy
```

**Comment by humberos** [comment]
thanks!
what android version ?

**Comment by rancidfrog** [comment]
n-mr1 branch shinano platform
**android-7.1.2_r11**

**Comment by humberos** [comment]
weird!
https://github.com/omnirom/android_system_sepolicy/blob/android-7.1/untrusted_app.te#L189-L204

-vfat

**Comment by rancidfrog** [comment]
Huh,
https://github.com/dirtyunicorns/android_system_sepolicy/blob/n7x/untrusted_app.te#L189-L204

**Comment by humberos** [comment]
well you have a revert
https://github.com/DirtyUnicorns/android_system_sepolicy/commit/63e1d3a00ca10eb7eef0826166a85db457f18b91

**Comment by humberos** [comment]
it should be fine using aosp sources.

**Comment by rancidfrog** [comment]
Okay thank you for the quick response

**Pull request merged**
