### PR TITLE
sepolicy: Use vendor_file_type for executables in /vendor

### PR DESCRIPTION
**Pull request by luk1337**

### CODE REVIEW

**Comment by luk1337** [comment]
We /may/ want to do the same for executables in /odm/bin but I didn't touch that for now.

**Comment by luk1337** [comment]
@jerpelea review?

**Comment by jerpelea** [comment]
odm and vendor should be on the same permission
@AdFad666

**Comment by luk1337** [comment]
That's why I added /odm rules to second change.

**Pull request merged**
